version: "3.7"

services:
  gisual-app:
    image: ekbostan111/gisual-app:latest
    ports:
      - "8000:8000"
    environment:
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
      MEMCACHED_PORT: ${MEMCACHED_PORT}
      MEMCACHED_USERNAME: ${MEMCACHED_USERNAME}
      MEMCACHED_PASSWORD: ${MEMCACHED_PASSWORD}
      MEMCACHED_USE_SSL: ${MEMCACHED_USE_SSL}
      VALID_API_KEYS: ${VALID_API_KEYS}
      SECRET_KEY: ${SECRET_KEY}
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
      restart_policy:
        condition: on-failure
