name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Docker Swarm
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DOCKER_HOST: "ssh://ec2-user@3.86.237.39"
        run: |
          echo "${SSH_KEY}" > key.pem
          chmod 400 key.pem
          scp -i key.pem docker-compose.yml ec2-user@3.86.237-39:/home/ec2-user/
          ssh -i key.pem ec2-user@3.86.237.39 "docker stack deploy -c /home/ec2-user/docker-compose.yml gisual-stack"
